version: "3.7"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - STAGE=${STAGE}
        - REACT_APP_PROJECT_NAME=${REACT_APP_PROJECT_NAME}
        - REACT_APP_LANGUAGE=${REACT_APP_LANGUAGE}
        - REACT_APP_THEME=${REACT_APP_THEME}
        - REACT_APP_API=${REACT_APP_API}
        - REACT_APP_COPYRIGHT_COMPANY=${REACT_APP_COPYRIGHT_COMPANY}
        - REACT_APP_COPYRIGHT_DATE=${REACT_APP_COPYRIGHT_DATE}
    stdin_open: true
    env_file:
      - docker-variables.production.env
    ports:
      - "${CLIENT_PORT}:3000"
    networks:
      - shorty-production
  database:
    image: postgres
    env_file:
      - docker-variables.production.env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - shorty-production
    volumes: 
      - shorty-production:/var/lib/postgresql/data
  shorty-service:
    build: ./shorty-service
    env_file:
      - docker-variables.production.env
    ports: 
      - "${SHORTY_PORT}:${SHORTY_PORT}"
    networks:
      - shorty-production
    depends_on:
      - database
networks: 
  shorty-production:
    driver: bridge
volumes: 
  shorty-production:
    driver: local