name: Run tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # The type of node version that the job will run on
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Run install and bootstrap steps 
      - run: npm ci
      # Run test client step
      - name: Test client
        run: npm test
        working-directory: client
        env:
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_PROJECT_NAME: Shorty DEV
          REACT_APP_STAGE: dev
          REACT_APP_LANGUAGE: en
          REACT_APP_THEME: classic
          REACT_APP_API: http://localhost:8000/api
          REACT_APP_COPYRIGHT_COMPANY: SHORTY
          REACT_APP_COPYRIGHT_DATE: 2021

      # Run test client step
      - name: Test shorty service
        run: npm test
        working-directory: shorty-service

